[package]
name = "svc-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt = "0.13"
jsonwebtoken = "8"
serde = {version = "1", features =["derive"]}
chrono = "0.4"
